
child = {
    'id': 27,
    'description': 'Main',
    'parent_id': 0,
    'url': 'master',
    'order': 2,
    'conf': 'hdr',
    'icon': 'heart',
    'isactive': 1,
    'isoption': 0
}, {
    'id': 29,
    'description': 'Product',
    'parent_id': 0,
    'url': 'productmaster',
    'order': 4,
    'conf': 'hdr',
    'icon': 'cubes',
    'isactive': 1,
    'isoption': 0
}, {
    'id': 30,
    'description': 'Documents',
    'parent_id': 0,
    'url': 'documents',
    'order': 3,
    'conf': 'hdr',
    'icon': 'folder',
    'isactive': 1,
    'isoption': 0
}, {
    'id': 37,
    'description': 'Security',
    'parent_id': 0,
    'url': 'security',
    'order': 6,
    'conf': 'hdr',
    'icon': 'key',
    'isactive': 1,
    'isoption': 1
}, {
    'id': 39,
    'description': 'Accounting',
    'parent_id': 0,
    'url': 'accounting',
    'order': 5,
    'conf': 'hdr',
    'icon': 'suitcase',
    'isactive': 1,
    'isoption': 0
}, {
    'id': 57,
    'description': 'Test only',
    'parent_id': 0,
    'url': 'error',
    'order': 7,
    'conf': 'hdr',
    'icon': 'not-set',
    'isactive': 0,
    'isoption': 0
}, {
    'id': 75,
    'description': 'Home',
    'parent_id': 0,
    'url': 'home',
    'order': 1,
    'conf': 'hdr',
    'icon': 'home',
    'isactive': 1,
    'isoption': 0
}, {
    'id': 78,
    'description': 'Scheduling',
    'parent_id': 0,
    'url': 'scheduling',
    'order': 8,
    'conf': 'hdr',
    'icon': 'clock-o',
    'isactive': 1,
    'isoption': 1
}, {
    'id': 87,
    'description': 'Love',
    'parent_id': 0,
    'url': 'love',
    'order': 9,
    'conf': 'vo',
    'icon': 'coffee',
    'isactive': 1,
    'isoption': 0
}, {
    'id': 110,
    'description': 'Phonebook',
    'parent_id': 0,
    'url': 'phonebook',
    'order': 10,
    'conf': 'hdr',
    'icon': 'lock',
    'isactive': 0,
    'isoption': 0
}, {
    'id': 195,
    'description': 'Sample',
    'parent_id': 0,
    'url': 'sampletest1',
    'order': 11,
    'conf': 'hdr',
    'icon': 'cloud',
    'isactive': 0,
    'isoption': 1
}, 